//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Assignment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Assignment()
        {
            this.assignmentsPerCourses = new HashSet<assignmentsPerCourse>();
            this.assignmentsPerStudentPerCourses = new HashSet<assignmentsPerStudentPerCourse>();
        }
    
        public int assignmentId { get; set; }
        public string description { get; set; }
        public System.DateTime subDateTime { get; set; }
        public int oralMark { get; set; }
        public int totalMark { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<assignmentsPerCourse> assignmentsPerCourses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<assignmentsPerStudentPerCourse> assignmentsPerStudentPerCourses { get; set; }
    }
}
