//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment2
{
    using System;
    using System.Collections.Generic;
    
    public partial class assignmentsPerStudentPerCourse
    {
        public int id { get; set; }
        public int assignmentId { get; set; }
        public int studentId { get; set; }
        public int courseId { get; set; }
    
        public virtual Assignment Assignment { get; set; }
        public virtual Cours Cours { get; set; }
        public virtual Student Student { get; set; }
    }
}
