//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment2
{
    using System;
    using System.Collections.Generic;
    
    public partial class trainersPerCourse
    {
        public int id { get; set; }
        public int trainerId { get; set; }
        public int courseId { get; set; }
    
        public virtual Cours Cours { get; set; }
        public virtual Trainer Trainer { get; set; }
    }
}
